version: '3'

services:
  nginx:
    container_name: 'nginx_web'
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${WORKSPACES}:/var/www/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    links:
      - php72:fpm72
      - php56:fpm56
    environment:
      - TZ=Asia/Shanghai
    networks:
      docker_net:
        ipv4_address: ${NGINX_IP}

  apache:
    container_name: 'apache_web'
    image: httpd:2.4
    ports:
      - "8080:80"
      - "4343:443"
    links:
      - php72:fpm72
      - php56:fpm56
    volumes:
      - ${WORKSPACES}:/var/www/:rw
      - ./conf/apache/:/usr/local/apache2/conf/:rw
      - ./log/apache/:/usr/local/apache2/logs/:rw
    networks:
      docker_net:
        ipv4_address: ${APACHE_IP}

  php72:
    container_name: 'php72'
    image: 5353920/php7.2.11:v1
    restart: always
    expose:
      - "9000"
      - "9501"
    volumes:
      - ${WORKSPACES}:/var/www/:rw
      - ./conf/php/php72.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.d/www72.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
    links:
      - mysql:mysql
      - redis:redis
    extra_hosts:
      - "www.wu.cn:172.100.0.2"
      - "shop.du.cn:172.100.0.2"
    networks:
      docker_net:
        ipv4_address: ${PHP72_IP}

  php56:
    container_name: 'php56'
    image: 5353920/php5.6.38:v1
    expose:
      - "9000"
      - "9501"
    volumes:
      - ${WORKSPACES}:/var/www/:rw
      - ./conf/php/php56.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.d/www56.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
    links:
      - mysql:mysql
      - redis:redis
    networks:
      docker_net:
        ipv4_address: ${PHP56_IP}

  mysql:
    container_name: 'mysql'
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mysql/:/var/lib/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      docker_net:
        ipv4_address: ${MYSQL_IP}

  redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      docker_net:
        ipv4_address: ${REDIS_IP}

  portainer:
    container_name: 'portainer'
    image: portainer/portainer:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./data/portainer/:/data:rw
    networks:
      docker_net:
        ipv4_address: ${PORTAINER_IP}

  composer:
    container_name: 'composer'
    image: composer/composer:php7
    command: install
    volumes:
      - ${WORKSPACES}:/var/www/:rw

networks:
  docker_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${DOCKER_SUBNET}"